# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neira.Boat')),
            ],
        ),
        migrations.AddField(
            model_name='heat',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='heat',
            name='url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='result',
            name='heat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neira.Heat'),
        ),
    ]
