# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neira', '0002_auto_20170421_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='raw_boat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='result',
            name='raw_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
