# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neira', '0003_auto_20170421_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='size',
            field=models.IntegerField(default=4),
        ),
    ]
