# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neira', '0004_boat_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='size',
        ),
    ]
