# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neira', '0005_remove_boat_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='size',
            field=models.CharField(choices=[('four', 'four'), ('eight', 'eight')], default='four', max_length=5),
        ),
    ]
