# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neira', '0006_boat_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='team',
            field=models.CharField(choices=[('b', 'boys'), ('g', 'girls'), ('n', 'novice')], default='b', max_length=1),
            preserve_default=False,
        ),
    ]
